//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id { get; set; }
        public string usuario1 { get; set; }
        public string contrasena { get; set; }
        public string estado { get; set; }
        public string token { get; set; }
        public Nullable<int> tipo_usuario { get; set; }
    }
}
